### PR TITLE
Add Manifest API to SDK

### PR DESCRIPTION
**Pull request by brprigge**
This PR adds manifest calls to the SDK.

Of note:
* LabelDownload object has been renamed Download.  LabelDownload as an object has been preserved to ease transition for anyone that is creating a LabelDownload object in a strongly typed way (though not sure why you would).
* Deprecated fields in the API are included in the Manifest result object, but marked obsolete.

Deserialization has been tested against an anonymized production response payload.
End-to-End has been tested against a production account with a Stamps.com USPS SCAN form.

### CODE REVIEW

**Comment by AnneOReilly** [comment]
@brprigge Thank you for the PR!  We will review this.

**Review by sushithegreat — APPROVED** [review]

**Comment by sushithegreat** [comment]
@brprigge can you also update the changelog and release number? Thank you!

**Comment by brprigge** [comment]
> @brprigge can you also update the changelog and release number? Thank you!

Version bumped and CHANGELOG line added.  Thanks!

**Comment by sushithegreat** [comment]
I apologize, I was sick for a few days and forgot to check in. I'll approve and merge shortly!

**Review by sushithegreat — APPROVED** [review]
🎉

**Comment by brprigge** [comment]
> I apologize, I was sick for a few days and forgot to check in. I'll approve and merge shortly!

No worries. I realized I hadn't actually tagged you on my reply anyway :-) 

Hope you are feeling better!

**Pull request merged**
