### PR TITLE
fix: add FundingSource & ParcelGuard as valid options for InsuranceProvider

### PR DESCRIPTION
**Pull request by avisser**
per https://www.shipengine.com/docs/shipping/add-insurance-to-shipment/

### CODE REVIEW

**Comment by avisser** [comment]
@semarj If you wouldn't mind reviewing. This'll be my 2nd PR. How many do I need before I get a T-shirt?

**Comment by avisser** [comment]
@jpill Can I get this tiny change merged? I'm a paying customer trying to use Parcel Guard in my dotnet app.

**Review by jpill — APPROVED** [review]

**Comment by avisser** [comment]
Thanks!

**Comment by avisser** [comment]
I just tried using the new release. The new values, `parcelguard` and `funding_source` don't work in the sandbox. When I pass either value, the response has the following error
```
{
  "RequestId": null,
  "ErrorSource": 1,
  "ErrorType": "business_rules",
  "ErrorCode": "unspecified",
  "ResponseMessage": null,
  "TargetSite": null,
  "Message": "A shipping carrier error occurred: Wallet not found for currency USD",
  "Data": {},
  "InnerException": null,
  "HelpLink": null,
  "Source": null,
  "HResult": -2146233088,
  "StackTrace": null
}
```

It works in Prod, but it seems like it should work in Test/Sandbox too.

I've validated this with Postman too. Is there a better place to file server bugs?

**Pull request merged**
